### ISSUE TITLE
Revenir à 1 à chaque changement de période

### ISSUE THREAD

**Issue by rastapopougros** [nursit/factures#1]
Hello,
pour dire que normalement, d'après les règles obligatoires en France (cf service-public.fr), le numéro de facture doit être chronologique **et sans trou**.

Or là le numéro généré par défaut utilise directement l'id SQL tel quel, ce qui fait qu'à chaque changement de période (que l'on utilise en préfixe), bah ça ne recommence pas à zéro (enfin à 1).

Déjà, je pense que le préfixe de période est trop précis, généralement l'année suffit ou à la limite avec le mois, mais pas jusqu'au jour.

Ensuite pour revenir à 1, moi je fais ça actuellement : 
- je cherche la période précédente (l'année précédente chez moi)
- je cherche l'id_facture de la dernière facture de la période précédente
- je le retire de l'id de la nouvelle facture

``` php
$time = strtotime($date_paiement);
$annee = date("Y", $time);
$annee_prec = intval($annee) - 1;

// On va chercher l'id SQL de la dernière facture de l'année précédente
// Pour repartir à 1 à chaque changement de période
if ($id_prec = intval(sql_getfetsel('id_facture', 'spip_factures', "date_paiement like '{$annee_prec}%'", '', 'date_paiement desc'))) {
	$id_facture = $id_facture - $id_prec;
}

$num = str_pad($id_facture, 5, '0', STR_PAD_LEFT);

return "F".$annee.'-'.$num;
```

Et là dès qu'on change d'année, ça recommence bien à 1.

**Comment by Cerdic** [comment]
Non justement ce faisant tu crées un trou de numéro au changement d'année et rien ne dit à l'administration fiscale que tu n'es pas venu à posteriori supprimer ou ajouter une facture en fin d'année, ce qu'elle veut justement pouvoir vérifier.

Le numéro par défaut est constitué de la date, utilisée par les humains, et d'un numéro d'ordre incrémental consécutif.
Ainsi l'administration fiscale peut vérifier la continuité, et les humains qui doivent traiter les factures peuvent retrouver facilement les infos grâce à la date qui est la purement décorative.

**Comment by rastapopougros** [comment]
Totalement faux ! :D 

Ce que je dis précédemment est l'exemple **précis** exposé sur le site officiel sur service public dans le chapitre "Facturation => Numérotation".

Je cite : 

> Il est également possible d'émettre des factures utilisant par exemple un préfixe par année (2014-XX) ou par année et mois (2014-01-XX), ce qui facilite l'archivage. **Une numérotation annuelle repart à zéro tous les ans** (par exemple, la dernière facture d'une année la n°2015-850 est suivie de la première facture de l'année suivante n°2016-001) ; **une numérotation mensuelle repart à zéro chaque mois**.

C'est plutôt clair non ?

**Comment by Cerdic** [comment]
Ah, tant mieux si l'administration accepte le retour à zéro, mais il n'est pas obligatoire. En l’occurrence on est encore plus clair en remettant jamais à zéro le numéro incrémenté.
Mon logiciel de facturation me fait des numéros préfixés par l'année-mois, sans jamais remettre à zéro le compteur au changement d'année.

**Comment by rastapopougros** [comment]
Ah ok, moi en fait c'était une demande du comptable, et du coup je suis aussi allé voir la doc officielle citée plus haut, et qui donnait le même exemple. Donc moi j'ai suivi tout ça à la lettre… :)

Mais tant mieux si ce n'est pas obligatoire ni dans un sens ni dans l'autre !
