### ISSUE TITLE
Utiliser date_transaction plutôt que date_paiement

### ISSUE THREAD

**Issue by rastapopougros** [nursit/factures#2]
Suivant le mode de paiement, le prestataire peut parfois renvoyer une date_paiement dans le futur.

Du coup la facture se retrouve elle aussi avec une date dans le futur *sauf que* sa génération, du HTML et de son numéro unique (qui doit se suivre sans trou), elle se fait *tout de suite*, au moment où on revient avec un paiement validé. On a donc une facture fabriquée ce jour même, mais avec une date future.

Pour un même mois, quand on donne au comptable les factures classées par date, il *peut* donc y avoir des trous dans les numéros générés (pas obligatoirement : ça arrive quand on a un mélange de paiement SEPA et de paiement classique qui eux ont toujours la bonne date).

Il faudrait donc prendre la date de début de transaction pour mettre dans la facture.

(PS : ça c'est pour les factures futures qui suivront, après si quelqu'un a une idée pour corriger les anciennes factures… facile de corriger le champ SQL à la main, mais pas le HTML généré qui lui est toujours faux.)

**Comment by Cerdic** [comment]
On ne peut pas prendre non plus la date_transaction, car elle peut-être située dans le passé de plusieurs jours/semaines/mois dans le cas des paiements par chèque.
Par ailleurs le champ SQL de la table spip_factures est date_paiement, donc je pense que le mieux c'est:
* ajouter un champ date qui sera la date de la facture, renseigné avec la date courante au moment de la création de la facture (donc ni la date_transaction ni la date_paiement)
* l'initialiser avec date_paiement pour l'upgrade de base
* l'utiliser pour numeroter les factures
* dans le squelette des factures distinguer aussi la date de la facture et la date_paiement qui sera indiquée dans la mention "Facture acquitée le ...."

**Comment by rastapopougros** [comment]
Ok, super merci !
Et donc pour celleux qui ont un squelette qui génère un CSV pour les comptables, il faut utiliser aussi le champ "date" pour ne sortir sur les trucs du mois voulu. Et là on ne devrait plus avoir de trou dans les numéros d'un même mois sorti.

Par contre, avant de migrer en 1.4.0, il faudrait peut-être que je transforme mes anciennes dates de paiement en date de début de la transaction (je crois pas que je peux faire ça en une requête SQL…) mais je vais demander si ça a déjà été donné à la comptable avant… Parce que pour l'instant ya bien plein de trous de numéros dans le CSV "février" et le CSV "mars".
